# Source: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven
name: Publish package to the Maven Central Repository
on:
  release:
    types: [ created ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: |
            8
            11

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          # Avoid caching generated artifacts
          path: |
            ~/.m2/repository/*
            !~/.m2/repository/com/github/cowwoc/pouch
          key: ${{ runner.OS }}-maven-${{ hashFiles("**/pom.xml") }}
          restore-keys: |
            ${{ runner.OS }}-maven-

      - name: Show versions
        run: |
          java --version
          ./mvnw --version

      - name: Build
        run: ./mvnw install -e

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: |
            8
            11
          server-id: maven-central-releases
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Show versions
        run: |
          java --version
          ./mvnw --version
          cat ~/.m2/toolchains.xml

      - name: Build
        run: ./mvnw install -e

      - name: Configure Git User
        run: |
          git config user.email "cowwoc2020@gmail.com"
          git config user.name "Gili"

      - name: Maven Release
        run: mvn release:prepare release:perform --batch-mode
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}